resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: patrickcrocker/maven-resource
    tag: latest
resources:
  - name: core-repository
    type: git
    source:
      uri: https://github.com/kodokojo/kodokojo.git
  - name: test-repository
    type: git
    source:
      uri: https://github.com/kodokojo/kodokojo-test.git
  - name: api-repository
    type: git
    source:
      uri: https://github.com/kodokojo/api-manager.git
  - name: core-nexus
    type: maven-resource
    source:
      url: http://192.168.99.100:8081/repository/maven-snapshots/
      username: admin
      password: admin123
      artifact: io.kodokojo:kodokojo:jar
  - name: test-nexus
    type: maven-resource
    source:
      url: http://192.168.99.100:8081/repository/maven-snapshots/
      username: admin
      password: admin123
      artifact: io.kodokojo:test-utility:jar
#  - name: api-nexus
#    type: maven-resource
#    source:
#      url: http://192.168.99.100:8081/repository/maven-snapshots/
#      username: admin
#      password: admin123
#      artifact: io.kodokojo:api:jar:runnable
  - name: api-image
    type: docker-image
    source:
      repository: kodokojo/api
      username: {{dockerLogin}}
      password: {{dockerPassword}}

jobs:
- name: build-core
  plan:
  - get: core-repository
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
          tag: 3-jdk-8-alpine
      inputs:
        - name: core-repository
      outputs:
        - name: core-built
      run:
        path: sh
        args:
        - -exc
        - |
          cd core-repository
          ls -la
          cp src/main/concourse/maven/settings.xml /root/.m2/
          cat /root/.m2/settings.xml
          mvn install
          cp target/kodokojo-1.2.0-SNAPSHOT.jar ../core-built/
          echo "1.2.0-SNAPSHOT" >> ../core-built/version
          ls -l ../core-built/
          cat ../core-built/version
  - put: core-nexus
    params:
      file: core-built/kodokojo-*.jar
      version_file: core-built/version

- name: build-test
  plan:
    - aggregate:
      - get: test-repository
        trigger: true
      - get: core-repository
        trigger: true
        passed: [build-core]
      - get: core-nexus
    - task: build
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: maven
            tag: 3-jdk-8-alpine
        inputs:
          - name: test-repository
        outputs:
          - name: test-built
        run:
          path: sh
          args:
          - -exc
          - |
            pwd
            ls -la
            cd test-repository
            cp src/main/concourse/maven/settings.xml /root/.m2/
            mvn install
            cp target/api-1.0-SNAPSHOT-runnable.jar ../test-built/
            echo "1.0-SNAPSHOT" >> ../test-built/version
    - put: test-nexus
      params:
        file: test-built/api-*.jar
        version_file: core-built/version

- name: build-api
  plan:
    - aggregate:
      - get: api-repository
        trigger: true
      - get: core-repository
        trigger: true
        passed: [build-core, build-test]
      - get: core-nexus
      - get: test-nexus
    - task: build
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: maven
            tag: 3-jdk-8-alpine
        inputs:
          - name: core-built
          - name: test-built
          - name: api-repository
        outputs:
          - name: api-built
        run:
          path: sh
          args:
          - -exc
          - |
            mkdir -p api-repository/root/.m2/repository/
            cp -R /test-built/root/.m2/repository/ api-repository/root/.m2/repository/
            cd api-repository
            mvn clean install
            cp target/api-*-runnnable.jar ../built/
            cp src/main/docker/local/* ../built/
    - put: api-image
      params:
        build: built
